#!/bin/bash
# EFI / GRUB boot layout (ROCKNIX ABL style).
set -euo pipefail

EFI_GRUB_SEARCH_SNIPPET='# Find the FAT boot partition that contains the Armbian kernel image.
search --no-floppy --set=root --file /Image
if [ -z "$root" ]; then
    echo "ERROR: /Image not found on any partition."
    echo "Copy the full output folder contents onto the SD boot partition."
    sleep 3
fi
'

enhance_cmdline_for_efi() {
    local cmdline="$1" token key
    local -a extras=(
        arm64.nopauth
        efi=noruntime
        fbcon=rotate:1
        console=ttyMSM0,115200n8
    )
    local -A present=()

    for token in ${cmdline}; do
        key="${token%%=*}"
        present["${key}"]=1
    done

    for token in "${extras[@]}"; do
        key="${token%%=*}"
        [[ -n "${present[${key}]:-}" ]] || cmdline+=" ${token}"
    done

    echo "${cmdline# }"
}

_grub_cmdline_from_system() {
    local boot_root="${1:-/boot}"
    local cfg cmdline

    for cfg in \
        "${boot_root}/EFI/BOOT/grub.cfg" \
        "${boot_root}/boot/grub/grub.cfg"
    do
        [[ -f "${cfg}" ]] || continue
        cmdline="$(grep -E '^[[:space:]]*linux[[:space:]]' "${cfg}" 2>/dev/null | head -1 \
            | sed -E 's/^[[:space:]]*linux[[:space:]]+(\(\$root\)\/)?[^[:space:]]+[[:space:]]+//')"
        if [[ -n "${cmdline}" ]]; then
            enhance_cmdline_for_efi "${cmdline}"
            return 0
        fi
    done

    enhance_cmdline_for_efi "$(tr '\0' ' ' < /proc/cmdline)"
}

_grub_is_stub_cfg() {
    local cfg="$1"
    grep -qE '^[[:space:]]*configfile[[:space:]]' "${cfg}" 2>/dev/null
}

_patch_grub_cfg_file() {
    local cfg="$1" release="$2" primary_dtb="$3" device_choice="$4"
    local initrd="initrd.img-${release}"
    local tmp

    [[ -f "${cfg}" ]] || return 0

    if _grub_is_stub_cfg "${cfg}"; then
        echo "  $(basename "$(dirname "${cfg}")")/$(basename "${cfg}") (EFI stub — unchanged)" >&2
        return 0
    fi

    tmp="$(mktemp)"
    cp -f "${cfg}" "${tmp}"

    sed -i -E "s|^[[:space:]]*initrd[[:space:]]+.*|    initrd (\$root)/${initrd}|" "${tmp}"

    if [[ "${device_choice}" != "all" ]]; then
        sed -i -E "s|^[[:space:]]*devicetree[[:space:]]+.*|    devicetree (\$root)/${primary_dtb}|" "${tmp}"
    fi

    mv -f "${tmp}" "${cfg}"
    echo "  $(realpath --relative-to=/ "${cfg}" 2>/dev/null || echo "${cfg}") (initrd=${initrd})" >&2
}

_write_fallback_grub_cfg() {
    local dest="$1" release="$2" primary_dtb="$3" title="$4"
    local initrd="initrd.img-${release}"
    local cmdline

    cmdline="$(_grub_cmdline_from_system "${BOOT_SOURCE:-/boot}")"

    cat > "${dest}" <<EOF
# Generated by ayn-sm8550-kernel — EFI boot for ROCKNIX ABL
set timeout=5
set default=0

insmod part_gpt
insmod part_msdos
insmod fat
insmod linux
insmod gzio
insmod efi_gop
insmod efi_uga
insmod search
insmod search_fs_file

${EFI_GRUB_SEARCH_SNIPPET}
menuentry '${title}' {
    linux (\$root)/Image ${cmdline}
    initrd (\$root)/${initrd}
    devicetree (\$root)/${primary_dtb}
}
EOF
    echo "  $(basename "${dest}") (generated fallback)" >&2
}

assemble_efi_boot_extras() {
    local boot_dir="$1" release="$2" primary_dtb="$3" device_choice="$4"
    local boot_root="${BOOT_SOURCE:-/boot}"
    local efi_boot="${boot_dir}/EFI/BOOT"
    local main_grub="${boot_dir}/boot/grub"
    local src_efi src_main src_loader title
    local -a cfg_targets=()

    mkdir -p "${efi_boot}" "${main_grub}"

    title="Armbian"
    case "${device_choice}" in
        odin2)  title="AYN Odin 2" ;;
        portal) title="AYN Odin 2 Portal" ;;
        mini)   title="AYN Odin 2 Mini" ;;
        thor)   title="AYN Thor" ;;
    esac

    src_loader="${boot_root}/EFI/BOOT/BOOTAA64.EFI"
    if [[ -f "${src_loader}" ]]; then
        cp -f "${src_loader}" "${efi_boot}/BOOTAA64.EFI"
        echo "  EFI/BOOT/BOOTAA64.EFI" >&2
    else
        echo "  WARNING: ${src_loader} not found — copy BOOTAA64.EFI manually if needed" >&2
    fi

    src_efi="${boot_root}/EFI/BOOT/grub.cfg"
    src_main="${boot_root}/boot/grub/grub.cfg"

    if [[ -f "${src_efi}" ]]; then
        cp -f "${src_efi}" "${efi_boot}/grub.cfg"
        cfg_targets+=("${efi_boot}/grub.cfg")
    fi

    if [[ -f "${src_main}" ]]; then
        cp -f "${src_main}" "${main_grub}/grub.cfg"
        cfg_targets+=("${main_grub}/grub.cfg")
    elif [[ ! -f "${src_efi}" ]]; then
        _write_fallback_grub_cfg "${efi_boot}/grub.cfg" "${release}" "${primary_dtb}" "${title}"
        cfg_targets+=("${efi_boot}/grub.cfg")
    fi

    if [[ ${#cfg_targets[@]} -eq 0 ]]; then
        _write_fallback_grub_cfg "${efi_boot}/grub.cfg" "${release}" "${primary_dtb}" "${title}"
        cfg_targets+=("${efi_boot}/grub.cfg")
    fi

    local cfg
    for cfg in "${cfg_targets[@]}"; do
        _patch_grub_cfg_file "${cfg}" "${release}" "${primary_dtb}" "${device_choice}"
    done

    return 0
}
